description: 'This exporter connects to any libvirt daemon and exports per-domain
  metrics

  related to CPU, memory, disk and network usage.

  By default, this exporter listens on TCP port 9177.

  '
maintainer: Prometheus Charmers <prometheus-charmers@lists.launchpad.net>
name: prometheus-libvirt-exporter
provides:
  scrape:
    interface: http
requires:
  juju-info:
    interface: juju-info
    scope: container
resources:
  prometheus-libvirt-exporter:
    description: Prometheus-libvirt-exporter snap
    filename: prometheus-libvirt-exporter.snap
    type: file
series:
- xenial
- bionic
subordinate: true
summary: Prometheus libvirt exporter
tags:
- monitoring
