description: 'The Prometheus Pushgateway exists to allow ephemeral and batch jobs
  to

  expose their metrics to Prometheus. Since these kinds of jobs may not

  exist long enough to be scraped, they can instead push their metrics to

  a Pushgateway. The Pushgateway then exposes these metrics to Prometheus.

  '
maintainer: Prometheus Charmers <prometheus-charmers@lists.launchpad.net>
name: prometheus-pushgateway
provides:
  nrpe-external-master:
    interface: nrpe-external-master
    scope: container
  pushgateway-service:
    interface: http
series:
- xenial
- bionic
subordinate: false
summary: Prometheus pushgateway
tags:
- monitoring
