categories:
- misc
description: 'Prometheus is a systems and service monitoring system. It collects

  metrics from configured targets at given intervals, evaluates rule

  expressions, displays the results, and can trigger alerts if some

  condition is observed to be true.

  '
maintainer: Jacek Nykis <jacek.nykis@canonical.com>
name: prometheus
provides:
  nrpe-external-master:
    interface: nrpe-external-master
    scope: container
requires:
  alertmanager-service:
    interface: http
  target:
    interface: http
storage:
  metrics-block:
    description: Storage for prometheus data
    multiple:
      range: 0-1
    type: block
  metrics-filesystem:
    description: Storage for prometheus data
    location: /srv/prometheus
    multiple:
      range: 0-1
    type: filesystem
subordinate: false
summary: Monitoring system and timeseries database
tags:
- monitoring
